---
# handlers file for rsyslog
- name: Check if syslog.d exist
  stat: path=/etc/init.d/syslog
  register: service_status

- name: Stop Service
  service: name=syslog state=stopped
  when: service_status.stat.exists
  register: service_stopped

- name: restart rsyslog
  service: name=rsyslog state=restarted
  become: true
